version: '3'

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
#   environment - перечисление глобальных переменных для сервиса
    environment:
      - PORT=3000
      - HOST=https://timoshenskiy.com
#   MONGO_URL - урл базы данных, всегда имеет вид mongodb://{host}/{port}/{база данных}
      - MONGO_URL=mongodb://docker-template_api-db_1:27017/api
#   depends_on - указывает сервисы, которые должны быть запущены перед запуском
    depends_on:
      - api-db

  api-db:
    image: mongo:latest
# volumes - дополнительное хранилище вне контейнера для хранения данных и их шаринга между сервисами
    volumes:
      - mongodb_api:/data/db

# настройка позволяет использовать этот volume во всех сервисах
volumes:
  mongodb_api:
