version: '3'

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
#   environment - перечисление глобальных переменных для сервиса
    environment:
      - PORT=3000
      - HOST=https://timoshenskiy.com
#   MONGO_URL - урл базы данных, всегда имеет вид mongodb://{host}/{port}/{база данных}
      - MONGO_URL=mongodb://api_db:27017/api
#   depends_on - указывает сервисы, которые должны быть запущены перед запуском
    depends_on:
      - api-db

  api-db:
    image: mongo:latest
